app/models/base.py
from app.extensions import db

# Define a base model for other database tables to inherit

class Base(db.Model):

    __abstract__ = True

    date_created = db.Column(
        db.DateTime(),
        default=db.func.current_timestamp()
    )
    date_modified = db.Column(
        db.DateTime(),
        default=db.func.current_timestamp(),
        onupdate=db.func.current_timestamp()
    )

    def insert(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def update(self, data):
        db.session.update(data)
        db.session.commit()
    
    def expunge(self):
        db.session.expunge(self)

app/models/user.py
from app.extensions import db
from app.models.base import Base
class User(Base):
    __tablename__ = "Users"
 
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # user_id = db.Column(db.Integer(), unique = True)
    first_name = db.Column(db.String())
    last_name = db.Column(db.String())
    cell_phone = db.Column(db.String(12))

    def __init__(self, first_name:str, last_name:str, cell_phone:str):
        self.first_name = first_name
        self.last_name = last_name
        self.cell_phone = cell_phone
 
    def __repr__(self):
        return f"{self.first_name} {self.last_name} : {self.id} : {self.date_created}"

app/__init__.py
from flask import Flask, url_for, send_from_directory
from app.extensions import db
from config import config
from app.extensions import migrate

import os

from app.models import user

def create_app():
    
    app = Flask(__name__)
    app.config.from_object(config[os.environ.get("CONFIG_MODE")])
    
    # Initialize Flask extensions here

    with app.app_context():
        db.init_app(app)
        db.create_all()

        migrate.init_app(app, db)
        
        #Register blueprints here
        from app.main import bp as main_bp
        app.register_blueprint(blueprint=main_bp)

        from app.certificates import bp as certificates_bp
        app.register_blueprint(blueprint=certificates_bp, url_prefix="/certificates")
        
        from app.users import bp as users_bp
        app.register_blueprint(blueprint=users_bp, url_prefix="/users")

        from app.courses import bp as courses_bp
        app.register_blueprint(blueprint=courses_bp, url_prefix="/courses")
        
        @app.route('/favicon.ico')
        def favicon():
            return send_from_directory(
                directory=os.path.join(app.root_path, 'static'),
                path='static/favicon.ico', 
                mimetype='image/vnd.microsoft.icon'
            )

        @app.route('/test/')
        def test_page():
            return '<h1>Testing the Flask Application Factory Pattern</h1>'
        return app

app/app.py
from . import create_app

# from dotenv import dotenv_values
# config = dotenv_values(".env")

from dotenv import load_dotenv
load_dotenv() 

from .procesess import my_feature_thread
from threading import Thread

# t1 = Thread(target=my_feature_thread, args=())
# t1.start()
# t1.join()

app = create_app()

app/certificates/__init__.py
from flask import Blueprint

bp = Blueprint('certificates', __name__)

from app.certificates import routes

app/certificates/routes.py
from flask import render_template
from app.certificates import bp

# from app.extensions import db
# from app.models.post import Post

@bp.route('/')
def index():
    # posts = Post.query.all()
    return render_template('certificates/index.html', title="Certificados")#, posts=posts)

# @bp.route('/categories/')
# def categories():
#     return render_template('posts/categories.html')

app/controllers/users_controller.py
from app.queries import users_queries


def get_all_users()->list:
    return users_queries.get_all_users()

def add_new_user(first_name:str, last_name:str, cell_phone:str)->bool:
    from app.models.user import User
    new_user = User(
        first_name=first_name,
        last_name=last_name,
        cell_phone=cell_phone,
    )
    return users_queries.insert_user(user=new_user)

app/courses/__init__.py
from flask import Blueprint

bp = Blueprint('courses', __name__)

from app.courses import routes

app/courses/routes.py
from flask import render_template
from app.courses import bp

# from app.extensions import db
# from app.models.post import Post

@bp.route('/')
def index():
    # posts = Post.query.all()
    return render_template('courses/index.html', title="Cursos")#, posts=posts)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, current_app, send_from_directory, send_file, redirect, url_for
from app.main import bp
import qrcode
import os

@bp.route('/')
def index():
    return redirect(url_for('certificates.index'))

@bp.route('/qrgenerator')
def qr_generator()->None:
    text_for_qr = "this is a text for qr code"
    img = qrcode.make(text_for_qr)
    img.save("app/qr_generated/qrcode1.png")
    return '<h1>qr generated</h1>'

@bp.route('/uploads/<path:filename>', methods=['GET', 'POST'])
def download(filename):
    # Appending app path to upload folder path within app root folder
    folder='static'
    uploads = os.path.join(
        current_app.root_path,
        folder,
        'qr_generated'
        # app.config['UPLOAD_FOLDER']
    )
    # print(uploads)
    # filename_to_download = filename[0:filename.find(' '):]
    # print(filename_to_download)
    # Returning file from appended path
    # return send_from_directory(directory=uploads,path=filename)
    return send_file(download_name=filename, path_or_file=uploads+'/'+filename, as_attachment=True)
    # return render_template('index.html')

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from app.users import routes

app/users/routes.py
from flask import render_template, redirect, url_for
from app.users import bp

# from app.extensions import db
# from app.models.post import Post

@bp.route('/newUser/', methods=['POST'])
def newUser(user_data):
    print(user_data)
    return redirect(url_for('users.index'))

@bp.route('/')
def index():
    # posts = Post.query.all()
    users = [
        {
            'number':1,
            'first_name':"Sergio Rodrigo",
            'last_name': "Cardenas Rivera",
            'cell_phone': "+59177418588",
            'register_date':''
        },
        {
            'number':2,
            'first_name':"Leonardo Daniel",
            'last_name': "Cardona Camacho",
            'cell_phone': "+59171476453",
            'register_date':''
        },
        {
            'number':3,
            'first_name':"Gustavo",
            'last_name': "Garcia Coca",
            'cell_phone': "+59165748223",
            'register_date':''
        },
        {
            'number':4,
            'first_name':"Juvenal Christian",
            'last_name': "Quispe Reynaga",
            'cell_phone': "+59167859423",
            'register_date':''
        },
    ]

    from app.controllers.users_controller import get_all_users
    from app.controllers.users_controller import add_new_user
    
    for user in users:
        add_new_user(
            first_name=user['first_name'], 
            last_name=user['last_name'],
            cell_phone=user['cell_phone']
        )
    users_with_number = get_all_users()
    cont=0
    for u in users_with_number:
        cont+=1
        u.number=cont
    return render_template('users/index.html', users=users_with_number, title="Usuarios")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <title>{% block title %} {% endblock %} - FlaskApp</title> -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/main.css') }}">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    {% if title %}
        <title>App - {{title}}</title>
    {%else%}
        <title>App</title>
    {%endif%}
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('certificates.index')}}">
                    <img src={{url_for('static', filename='favicon.ico') }} alt="Logo" width="30" class="d-inline-block align-text-top">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a id="certificates" class="nav-link active" aria-current="page" href="{{ url_for('certificates.index')}}">Certificados</a>
                        </li>
                        <li class="nav-item">
                            <a id="users" class="nav-link" href="{{ url_for('users.index') }}"">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a id="courses" class="nav-link" href="{{ url_for('courses.index') }}"">Cursos</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
        <div style="height: 100%;">
            {% block content %} {% endblock %}
        </div>        
        <!-- <div class="fixed-bottom">
            this is footer
        </div> -->
        <footer class="container fixed-bottom bg-body-tertiary text-center text-lg-start">
            <!-- Copyright -->
            <!-- style="background-color: rgba(0, 0, 0, 0.05);" -->
            <div class="text-center p-3" >
              © 2024 Copyright:
              <a class="text-body" href="https://github.com/srodrigo23">Sergio Rodrigo</a>
            </div>
            <!-- Copyright -->
        </footer>
    </div>
    {% block javascript %}
        <script src="{{ url_for('static',filename='js/index.js') }}"></script>
    {% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

app/templates/certificates/index.html
{% extends 'base.html' %}

{% block content %}
    <span class="title">
        <h1>{% block title %} Certificates {% endblock %}</h1>
    </span>
    <div class="questions">
        <h2>Certificates Blueprint</h2>
    </div>
{% endblock %}

app/templates/courses/index.html
{% extends 'base.html' %}

{% block content %}
    <span class="title">
        <h1>{% block title %} Courses {% endblock %}</h1>
    </span>
    <div class="questions">
        <h2>Courses Blueprint</h2>
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <!-- <span class="title"><h1>{% block title %} Programa certificados{% endblock %}</h1></span> -->
        <div class="content">
            {% for value in data %}
                <div><button>{{value}}</button> </div>
            {% endfor %}
            <a class="btn btn-outline-primary" href="{{ url_for('main.download', filename="qrcode1.png") }}" target="_blank"><i class="bi bi-qr-code"></i></a>
            <a class="btn btn-outline-primary" href="{{ url_for('main.download', filename="qrcode1.png") }}" target="_blank"><i class="bi bi-filetype-pdf" alt="Certificado"></i></a>
        </div>
    </div>
{% endblock %}

app/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="flex-column">
        <!-- <h1 class="text-center">Center aligned text on all viewport sizes.</h1> -->
        <div class="d-flex justify-content-center m-5">
            <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="bi bi-person-add"></i> Nuevo Usuario </button>
        </div>
        <div class="container-lg px-5">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Fecha de registro</th>
                        <th scope="col">Apellidos</th>
                        <th scope="col">Nombres</th>
                        <th scope="col">Celular</th>
                        <th scope="col">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <th scope="row">{{user['number']}}</th>
                        <td>{{user['date_created']}}</td>
                        <td>{{user['last_name']}}</td>
                        <td>{{user['first_name']}}</td>
                        <td>{{user['cell_phone']}}</td>
                        <td>
                            <!-- href="{{ url_for('main.download', filename="qrcode1.png")}}" target="_blank" -->
                            <a class="btn btn-outline-primary"><i class="bi bi-pen-fill"></i></a>
                            <a class="btn btn-outline-secondary"><i class="bi bi-file-earmark-arrow-down-fill"></i></a>
                            <a class="btn btn-outline-danger"><i class="bi bi-person-x-fill"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Nuevo Usuario</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="inputApellPat" class="form-label">Apellido Paterno</label>
                            <input type="text" class="form-control" id="apellPat" aria-describedby="apellPatHelp">
                            <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                        </div>
                        <div class="mb-3">
                            <label for="inputApellMat" class="form-label">Apellido Materno</label>
                            <input type="text" class="form-control" id="apellMat" aria-describedby="apellMatHelp">
                            <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                        </div>
                        <div class="mb-3">
                            <label for="inputfirstName" class="form-label">Primer Nombre</label>
                            <input type="text" class="form-control" id="firstName" aria-describedby="firstNameHelp">
                            <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                        </div>
                        <div class="mb-3">
                            <label for="inputsecondName" class="form-label">Segundo Nombre</label>
                            <input type="text" class="form-control" id="secondName" aria-describedby="secondNameHelp">
                            <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                        </div>
                        <div class="mb-3">
                            <label for="inputCellPhone" class="form-label">Número de Celular</label>
                            <input type="text" class="form-control" id="cellPhone" aria-describedby="cellPhoneHelp">
                            <!-- <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> -->
                        </div>
                        <!-- <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Password</label>
                            <input type="password" class="form-control" id="exampleInputPassword1">
                        </div> -->
                        <!-- <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div> -->
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}